### ISSUE TITLE
后台管理系统点击返回，不会返回，怎么做到的

### ISSUE THREAD

**Issue by dolphinfine** [mvpzx/elapse#2]
只想知道你是怎么操作这个返回按钮的。

**Comment by mvpzx** [comment]
可以具体说一下是那个哪个位置吗？有截图的话更好

**Comment by dolphinfine** [comment]
我说的是登录页面，没有登录。从github过去的，但是却不能返回github。怎么做到的

**Comment by mvpzx** [comment]
进了`登录页面`，`vue-router`的导航守卫会被触发，我在这里做了拦截，

**Comment by dolphinfine** [comment]
原来如此。返回的时候Url不断添加login%3Fredirect%3D%252F，感觉不是很好，变得越来越长。

**Comment by mvpzx** [comment]
确实，这应当算是个bug，我会去修复它
