### ISSUE TITLE
Vue的封装组件样式从哪里引进去？

### ISSUE THREAD

**Issue by Niofh** [mvpzx/elapse#3]
Vue的组件样式从哪里引进去？

**Comment by mvpzx** [comment]
可以看一下`src/theme`的结构，然后再看一下`build/util.js`文件内容，我在其中配置了`sass-resources-loader`，这样便实现了全局样式

**Comment by Niofh** [comment]
如果不用sass，怎么做？

**Comment by mvpzx** [comment]
那就看一下有没有相应的`[xxx]-resources-loader`，没有的话就在使用的地方引入一下
